apiVersion: apps/v1
kind: Deployment
metadata: 
  name: robot-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: robot
  template: 
    metadata:
      labels:
        app: robot
    spec:
      containers: 
      -
        image: mailmepavi93/robot:latest
        name: robot-container
        ports:
        -
          containerPort: 8082
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: robot-netpol
spec:
  ingress:
  -
    ports:
    -
      port: 8082
  podSelector:
    matchLabels:
      app: robot
---
apiVersion: v1
kind: Service
metadata: 
  name: robot-svc
spec:
  ports:
  -
    nodePort: 30001
    port: 80
    targetPort: 8082
  selector:
    app: robot
  type: NodePort
