name: CI-robo
on:
  push: 
    branches: [master]
jobs: 
  docker: 
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v2
    -
      run: |
        set -x
        docker build -t robospringpavi --no-cache .
        docker run --rm -d robospringpavi
        while true
          do 
            sleep 1
            docker ps | grep Up && break
          done
        while true
          do 
            sleep 1
            docker exec $( docker ps -q ) ps | grep "java -jar" && break
          done
